version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1
   
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: lein deps
      - run:
          name: test it
          command: lein test
   